language: php

php:
- 7.2

before_script:
- php composer install
- php bin/console doctrine:schema:create
- php bin/console initialize:database
- php bin/console fos:user:create test test@example.com test
- php bin/console fos:user:promote test ROLE_ADMIN

script: phpunit --coverage-text