language: php

php:
- 7.2

services:
- mysql
before_install:
- mysql -e 'CREATE DATABASE symfony;'
before_script:
- cp app/config/parameters.yml.dist app/config/parameters.yml
- composer install
- php bin/console doctrine:database:create --env=test
- php bin/console doctrine:schema:create
- php bin/console initialize:database
- php bin/console fos:user:create test test@example.com test
- php bin/console fos:user:promote test ROLE_ADMIN
- php bin/console download:all

script: phpunit --coverage-text