app:
    resource: '@AppBundle/Controller/'
    type: annotation
#    prefix:   /{_locale}
#    requirements:
#        _locale: '%routing_languages%'

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing/swaggerui.xml"
    prefix:   /api/doc

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"