easy_admin:
    site_name: 'LunchBot'
    entities:
        Meal:
            class: AppBundle\Entity\Meal
        Restaurant:
            class: AppBundle\Entity\Restaurant
        Tag:
            class: AppBundle\Entity\Tag
        User:
            class: AppBundle\Entity\User
            label: 'Users'
            list:
                  title: 'Users'
                  fields:
                        - firstname
                        - lastname
                        - username
                        - email
                        - enabled
                        - lastLogin
            edit:
                  fields:
                        - firstname
                        - lastname
                        - username
                        - email
                        - enabled
                        - lastLogin
                        - { property: 'plainPassword', type: 'text', type_options: { required: false } }
                        - { property: 'roles', type: 'choice', type_options: { multiple: true, choices: { 'ROLE_USER': 'ROLE_USER', 'ROLE_ADMIN': 'ROLE_ADMIN' } } }
                  form_options: { validation_groups: ['Profile'] }
            new:
                  fields:
                        - firstname
                        - lastname
                        - username
                        - email
                        - enabled
                        - lastLogin
                        - { property: 'plainPassword', type: 'text', type_options: { required: true } }
                        - { property: 'roles', type: 'choice', type_options: { multiple: true, choices:  { 'ROLE_USER': 'ROLE_USER', 'ROLE_ADMIN': 'ROLE_ADMIN' } } }
                  form_options: { validation_groups: ['Registration'] }