fos_rest:
    routing_loader:
        default_format: json
        include_format: true
    param_fetcher_listener: force
    body_listener: true
    allowed_methods_listener: true
    view:
        view_response_listener: 'force'
        formats:
            json: true
    format_listener:
        rules:
           - { path: '^/api/', priorities: [ 'json' ], fallback_format: json, prefer_extension: false }
           - { path: '^/', stop: true }
    versioning: true