fos_user:
    db_driver: orm # other valid values are 'mongodb' and 'couchdb'
    firewall_name: main
    user_class: AppBundle\Entity\AdminUser
    service:                               # this lines
            mailer: fos_user.mailer.twig_swift # this lines
    from_email:
        address: "noreply@lunchbot.com"
        sender_name: "LunchBot"